package com.pdlpdl.pdlproxy.minecraft.gamestate.datagen;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.pdlpdl.pdlproxy.minecraft.gamestate.datagen.model.MinecraftBlockMappingInfo;
import com.pdlpdl.pdlproxy.minecraft.gamestate.datagen.model.MinecraftBlockMappingReport;
import com.pdlpdl.pdlproxy.minecraft.gamestate.datagen.model.MinecraftBlockMappingStateInfo;
import com.pdlpdl.pdlproxy.minecraft.gamestate.datagen.model.registries.MinecraftItemEntry;
import com.pdlpdl.pdlproxy.minecraft.gamestate.datagen.model.registries.MinecraftItemRegistry;
import com.pdlpdl.pdlproxy.minecraft.gamestate.datagen.model.registries.MinecraftRegistries;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;

/**
 * Map block names to states and item ids using the report files generated by the minecraft server.
 *
 * Refactored from PDL Powered.
 */
public class BlockIdMapper {

    public static final String DEFAULT_BLOCK_PREFIX = "minecraft:";

    private static final Logger DEFAULT_LOGGER = LoggerFactory.getLogger(BlockIdMapper.class);

    private Logger log = DEFAULT_LOGGER;

    private Map<String, MinecraftBlockMappingInfo> blockStatesByName = new HashMap<>();
    private Map<String, MinecraftBlockMappingStateInfo> defaultStateByName = new HashMap<>();
    private Map<Integer, MinecraftBlockMappingStateInfo> blocksByState = new HashMap<>();

    private Map<Integer, String> blockNameByState = new HashMap<>();

    private Map<String, Integer> itemIdByName = new HashMap<>();

//========================================
// Lifecycle
//========================================

    public void loadBlocksReportFile(InputStream blocksReportInputStream) {
        try {
            ObjectMapper objectMapper = new ObjectMapper();

            MinecraftBlockMappingReport report = objectMapper.readValue(blocksReportInputStream, MinecraftBlockMappingReport.class);

            this.processBlocksReport(report);

            this.log.info("Loaded the blocks report file; block-state-count={}", this.blocksByState.size());
        } catch (Exception exc) {
            throw new RuntimeException("Failed to load block report file to map block names to IDs", exc);
        }
    }

    public void loadRegistriesFile(InputStream registriesReportInputStream) {
        try {
            ObjectMapper objectMapper = new ObjectMapper();

            MinecraftRegistries registries = objectMapper.readValue(registriesReportInputStream, MinecraftRegistries.class);

            this.processRegistries(registries);
        } catch (Exception exc) {
            throw new RuntimeException("Failed to load registries file to map item IDs by name", exc);
        }
    }

//========================================
// API
//========================================

    /**
     * Lookup the default block state for the block with the given name.
     *
     * @param blockName
     * @return
     */
    public Integer lookupDefaultBlockState(String blockName) {
        MinecraftBlockMappingStateInfo stateInfo = this.defaultStateByName.get(blockName);

        if (stateInfo != null) {
            return stateInfo.getId();
        }

        return null;
    }

    /**
     * Lookup an block name and return its item ID.  Items include blocks held in inventory.
     *
     * @param itemName
     * @return
     */
    public Integer lookupItemIdByName(String itemName) {
        return this.itemIdByName.get(itemName);
    }

    public String lookupBlockNameById(int blockStateNum) {
        return this.blockNameByState.get(blockStateNum);
    }

    public int getBlockStateCount() {
        return this.blocksByState.size();
    }

//========================================
// Internals
//========================================

    private void processBlocksReport(MinecraftBlockMappingReport report) {
        Map<String, MinecraftBlockMappingInfo> blockMap = report.getBlockMap();

        for (Map.Entry<String, MinecraftBlockMappingInfo> oneBlockMapping : blockMap.entrySet()) {
            String blockName = oneBlockMapping.getKey();
            MinecraftBlockMappingInfo blockMappingInfo = oneBlockMapping.getValue();

            this.blockStatesByName.put(blockName, blockMappingInfo);

            //
            // Iterate over the states for this block and add the mappings for each
            //
            for (MinecraftBlockMappingStateInfo stateInfo : blockMappingInfo.getStates()) {
                this.blocksByState.put(stateInfo.getId(), stateInfo);
                this.blockNameByState.put(stateInfo.getId(), blockName);

                if (stateInfo.getDefaultInd()) {
                    this.defaultStateByName.put(blockName, stateInfo);
                }
            }
        }
    }

    private void processRegistries(MinecraftRegistries registries) {
        MinecraftItemRegistry minecraftItemRegistry = registries.getItems();

        for (Map.Entry<String, MinecraftItemEntry> entry : minecraftItemRegistry.getEntries().entrySet()) {
            this.itemIdByName.put(entry.getKey(), entry.getValue().getProtocolId());
        }
    }
}
